const ADD_VERTEX = 'ADD_VERTEX';
const DELETE_VERTEX = 'DELETE_VERTEX';
const DRAG_VERTEX = 'DRAG_VERTEX';
const ADD_EDGE = 'ADD_EDGE';

export {
  ADD_VERTEX,
  DELETE_VERTEX,
  DRAG_VERTEX,
  ADD_EDGE
}
