const ADD_VERTEX = 'ADD_VERTEX';
const ADD_RELATION = 'ADD_RELATION';
const CREATE_GRAPH = 'CREATE_GRAPH';
const CHANGE_CURRENT_ACTION = 'CHANGE_CURRENT_ACTION';
const ADD_VERTEX_TO_BUFFER_EDGE = 'CREATE_EDGE';
const CLEAR_BUFFER_EDGE = 'CLEAR_BUFFER_EDGE';

export {
  ADD_VERTEX,
  ADD_RELATION,
  CREATE_GRAPH,
  CHANGE_CURRENT_ACTION,
  ADD_VERTEX_TO_BUFFER_EDGE,
  CLEAR_BUFFER_EDGE
}
