const ADD_VERTEX = 'ADD_VERTEX';

const ADD_RELATION = 'ADD_RELATION';

const DELETE_RELATION = 'DELETE_RELATION';

const CREATE_GRAPH = 'CREATE_GRAPH';

const SET_CURRENT_COMMAND = 'SET_CURRENT_COMMAND';

const ADD_VERTEX_TO_BUFFER_EDGE = 'CREATE_EDGE';

const CLEAR_BUFFER_EDGE = 'CLEAR_BUFFER_EDGE';

const SET_CURRENT_DRAGGABLE_SVG_SHAPE = 'SET_CURRENT_DRAGGABLE_SVG_SHAPE';

const SET_SVG_CONTAINER = 'SET_SVG_CONTAINER';

const LOG_LAST_COMMAND = 'LOG_LAST_COMMAND';

const UNDO_LAST_COMMAND = 'UNDO_LAST_COMMAND';

const REDO_LAST_COMMAND = 'REDO_LAST_COMMAND';

export {
  ADD_VERTEX,
  ADD_RELATION,
  DELETE_RELATION,
  CREATE_GRAPH,
  SET_CURRENT_COMMAND,
  ADD_VERTEX_TO_BUFFER_EDGE,
  CLEAR_BUFFER_EDGE,
  SET_CURRENT_DRAGGABLE_SVG_SHAPE,
  SET_SVG_CONTAINER,
  LOG_LAST_COMMAND,
  UNDO_LAST_COMMAND,
  REDO_LAST_COMMAND
}
