const ADD_VERTEX = 'ADD_VERTEX';
const ADD_RELATION = 'ADD_RELATION';
const CREATE_GRAPH = 'CREATE_GRAPH';
const SET_CURRENT_COMMAND = 'SET_CURRENT_COMMAND';
const ADD_VERTEX_TO_BUFFER_EDGE = 'CREATE_EDGE';
const CLEAR_BUFFER_EDGE = 'CLEAR_BUFFER_EDGE';
const SET_CURRENT_DRAGGABLE_SVG_SHAPE = 'SET_CURRENT_DRAGGABLE_SVG_SHAPE';
const SET_SVG_CONTAINER = 'SET_SVG_CONTAINER';
const LOG_LAST_COMMAND = 'LOG_LAST_COMMAND';
const POP_LAST_COMMAND = 'POP_LAST_COMMAND';

export {
  ADD_VERTEX,
  ADD_RELATION,
  CREATE_GRAPH,
  SET_CURRENT_COMMAND,
  ADD_VERTEX_TO_BUFFER_EDGE,
  CLEAR_BUFFER_EDGE,
  SET_CURRENT_DRAGGABLE_SVG_SHAPE,
  SET_SVG_CONTAINER,
  LOG_LAST_COMMAND,
  POP_LAST_COMMAND
}
