const COMMAND_HISTORY_CREATE = 'SET_COMMAND_HISTORY';
const COMMAND_HISTORY_LOG = 'COMMAND_HISTORY_LOG';
const COMMAND_HISTORY_UNDO = 'COMMAND_HISTORY_UNDO';

export {
  COMMAND_HISTORY_CREATE,
  COMMAND_HISTORY_LOG,
  COMMAND_HISTORY_UNDO
}
