const GRAPH_ADD_VERTEX = 'GRAPH_ADD_VERTEX';
const GRAPH_DELETE_VERTEX = 'GRAPH_DELETE_VERTEX';
const GRAPH_ADD_EDGE = 'GRAPH_ADD_EDGE';
const GRAPH_MOVE_VERTEX = 'GRAPH_MOVE_VERTEX';

const GRAPH_UNDO_REDO_MAP = {
  [`graph/${GRAPH_ADD_VERTEX}`]: `graph/${GRAPH_DELETE_VERTEX}`  // TODO: to use method
};

export {
  GRAPH_ADD_VERTEX,
  GRAPH_DELETE_VERTEX,
  GRAPH_ADD_EDGE,
  GRAPH_MOVE_VERTEX,
  GRAPH_UNDO_REDO_MAP
}
