const ADD_VERTEX = 'ADD_VERTEX';
const ADD_EDGE = 'ADD_EDGE';
const DELETE_VERTEX = 'DELETE_VERTEX';
const MOVE_VERTEX = 'MOVE_VERTEX';
const DELETE_EDGE = 'DELETE_EDGE';

export {
  ADD_VERTEX,
  ADD_EDGE,
  DELETE_VERTEX,
  MOVE_VERTEX,
  DELETE_EDGE
}
